### ISSUE TITLE
JSON lib not compatible with sensu-plugin-2.0.1

### ISSUE THREAD

**Issue by ketchoop** [sensu-plugins/sensu-plugins-influxdb#31]
I got this message when I try to execute your plugin:

```
/opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate sensu-plugin-2.0.0, because json-2.0.2 conflicts with json (< 2.0.0) (Gem::ConflictError)
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1408:in `activate'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/sensu/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /opt/sensu/embedded/bin/check-influxdb-query.rb:33:in `<main>
```

How can I resolve it? I'm not familiar with Ruby and Gem, so maybe there is some solution?

**Comment by majormoses** [comment]
Most of the plugins do not have support for `sensu-plugin` version 2 they are still pinned on < 2. We are gonna need to upgrade that soon but we need to give it some time to let people upgrade their sensu setup before breaking stuff.

**Comment by majormoses** [comment]
I am starting to run through all the repos and will be making breaking changes to address these types of issues. So you definitely will want to at least pin on the major version. To be clear it will take a while as I have a 100+ gems left to run through and ensure that they are good with ruby 2.4 at **install time** and then will need to run through all of the gems (which is closer to 200) and work out the issues with **run time** which is where your issue is. I am doing this on my free time and not a sensu employee. I would recommend pinning your `sensu-plugin` gem to 1.x in the meantime as this should solve your issue and then when everything has had the kinks worked out you can upgrade at that point.
